name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build WAR
        run: mvn clean package

      - name: Deploy to Tomcat
        run: copy target\*.war "C:\Program Files\Apache Software Foundation\Tomcat 10.1\webapps\"

      - name: Restart Tomcat
        run: |
          net stop Tomcat10
          net start Tomcat10
