name: Spring Boot CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Project (Maven)
        run: mvn clean package

      - name: Stop Tomcat (safe CMD)
        shell: cmd
        run: net stop Tomcat10 || echo Tomcat already stopped

      - name: Clean old deployment
        shell: cmd
        run: |
          del /Q "C:\Program Files\Apache Software Foundation\Tomcat 10.1\webapps\Project.war" || echo No WAR found
          rmdir /S /Q "C:\Program Files\Apache Software Foundation\Tomcat 10.1\webapps\Project" || echo No folder found

      - name: Deploy WAR to Tomcat
        shell: cmd
        run: copy target\*.war "C:\Program Files\Apache Software Foundation\Tomcat 10.1\webapps\Project.war"

      - name: Start Tomcat
        shell: cmd
        run: net start Tomcat10